# Generated by Django 5.1.5 on 2025-02-12 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('api_key', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('stored_at', models.DateTimeField()),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.currency')),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.provider')),
            ],
        ),
    ]
