# Generated by Django 5.1.5 on 2025-02-13 22:52

from django.db import migrations


def init_currencies(apps, schema_editor):
    Currency = apps.get_model('currency', 'Currency')

    # create BTC currency
    btc = Currency(name='Bitcoin')
    btc.save()

    # create ETH currency
    eth = Currency(name='Ethereum')
    eth.save()


def init_providers(apps, schema_editor):
    Provider = apps.get_model('currency', 'Provider')

    # create CoinMarketCap provideer
    coin_market = Provider(name='CoinMarketCap', api_key='NONE')
    coin_market.save()

    # create BlockChair provider
    block_chair = Provider(name='BlockChair', api_key='NONE')
    block_chair.save()


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_currencies),
        migrations.RunPython(init_providers),
    ]
