# Generated by Django 5.1.5 on 2025-02-14 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_init_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='currency_id',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='block',
            old_name='provider_id',
            new_name='provider',
        ),
    ]
